# Generated by Django 6.1.1 on 2026-09-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(choices=[('Romance', 'ROMANCE'), ('Aventura', 'AVENTURA'), ('Ação', 'AÇÃO'), ('Fantasia', 'FANTASIA'), ('Terror', 'TERROR'), ('Clássicos', 'CLÁSSICOS')], max_length=100),
        ),
    ]
