# Generated by Django 6.1.1 on 2026-09-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoria_descricao_alter_categoria_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
    ]
