# Generated by Django 6.1.1 on 2026-09-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_remove_categoria_descrição'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
