# Generated by Django 6.1.1 on 2026-09-14 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField()),
                ('status', models.CharField(choices=[('Disponivel', 'DISPONIVEL'), ('Alugado', 'ALUGADO'), ('Reservado', 'RESERVADO')], default='DISPONIVEL', max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
        ),
    ]
